project:
  type: book
  output-dir: _book

book:
  title: "Application of Econometric Models with RStudio"
  author: "Deri Siswara"
  date: today
  chapters:
    - index.qmd
    - 01-Bab1.qmd
    - 02-Bab2.qmd
    - 03-Bab3.qmd
    - 04-Bab4.qmd
    - 05-Bab5.qmd
    - 06-Bab6.qmd
    - 07-Bab7.qmd
    - 08-Bab8.qmd
    - 09-Bab9.qmd
  
  sidebar:
    style: docked
    background: light
    
  repo-url: https://github.com/derisiswara/econometricsbook
  repo-actions: [edit, issue]
  
  downloads: [pdf, epub]

  cover-image: images/cover.jpeg
  favicon: images/cover.jpeg
  page-navigation: true
  search: true

bibliography: [book.bib, packages.bib]
csl: chicago-fullnote-bibliography.csl

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: style.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-tools: true
    code-copy: true
    highlight-style: github
    
  pdf:
    documentclass: book
    toc: true
    number-sections: true
    colorlinks: true
    include-in-header:
      - preamble.tex
    
  epub:
    toc: true
    number-sections: true

execute:
  freeze: auto
  cache: true

