{
  "hash": "3860eb8a464954e8eb51cb890f580ee0",
  "result": {
    "engine": "knitr",
    "markdown": "# Panel Data Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndatapanel = read_excel(\"Data/Bab 5/Data Panel.xlsx\")\nhead(datapanel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province  year realgdp population investment   hdi\n  <chr>    <dbl>   <dbl>      <dbl>      <dbl> <dbl>\n1 Aceh      2010 101545.    4523100       82.3  67.1\n2 Aceh      2011 104874.    4619000      463.   67.4\n3 Aceh      2012 108915.    4715100     1726.   67.8\n4 Aceh      2013 111756.    4811100     4785.   68.3\n5 Aceh      2014 113488.    4906800     5497.   68.8\n6 Aceh      2015 112672.    5002000     4485.   69.4\n```\n\n\n:::\n:::\n\n\n## Static Panel Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plm)\nmodel1 = log(realgdp) ~ log(population) + log(investment) + log(hdi)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# time vs individual effect\npFtest(model1, data = datapanel, effect = \"time\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for time effects\n\ndata:  model1\nF = 3.1305, df1 = 6, df2 = 221, p-value = 0.005777\nalternative hypothesis: significant effects\n```\n\n\n:::\n\n```{.r .cell-code}\npFtest(model1, data = datapanel, effect = \"individual\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for individual effects\n\ndata:  model1\nF = 824.45, df1 = 32, df2 = 195, p-value < 2.2e-16\nalternative hypothesis: significant effects\n```\n\n\n:::\n\n```{.r .cell-code}\npFtest(model1, data = datapanel, effect = \"twoways\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for twoways effects\n\ndata:  model1\nF = 812.75, df1 = 38, df2 = 189, p-value < 2.2e-16\nalternative hypothesis: significant effects\n```\n\n\n:::\n:::\n\n\n### Pooled OLS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPOLS <- plm(model1, data = datapanel, \n                      index = c(\"province\", \"year\"), \n                      effect = \"twoways\", model = \"pooling\")\nsummary(POLS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPooling Model\n\nCall:\nplm(formula = model1, data = datapanel, effect = \"twoways\", model = \"pooling\", \n    index = c(\"province\", \"year\"))\n\nBalanced Panel: n = 33, T = 7, N = 231\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-0.802950 -0.288399 -0.071922  0.204733  1.211596 \n\nCoefficients:\n                  Estimate Std. Error t-value  Pr(>|t|)    \n(Intercept)     -14.998414   1.789923 -8.3794 5.578e-15 ***\nlog(population)   0.761682   0.034219 22.2592 < 2.2e-16 ***\nlog(investment)   0.200796   0.018761 10.7031 < 2.2e-16 ***\nlog(hdi)          3.187128   0.432136  7.3753 3.050e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    316.63\nResidual Sum of Squares: 37.477\nR-Squared:      0.88164\nAdj. R-Squared: 0.88008\nF-statistic: 563.624 on 3 and 227 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n### Fixed Effects Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFEM <- plm(model1, data = datapanel, \n                      index = c(\"province\", \"year\"), \n                      effect = \"twoways\", model = \"within\")\n\nsummary(FEM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects Within Model\n\nCall:\nplm(formula = model1, data = datapanel, effect = \"twoways\", model = \"within\", \n    index = c(\"province\", \"year\"))\n\nBalanced Panel: n = 33, T = 7, N = 231\n\nResiduals:\n      Min.    1st Qu.     Median    3rd Qu.       Max. \n-0.1065933 -0.0108718  0.0010591  0.0107126  0.1302578 \n\nCoefficients:\n                  Estimate Std. Error t-value Pr(>|t|)  \nlog(population) -0.4403249  0.2194092 -2.0069  0.04619 *\nlog(investment) -0.0046652  0.0039298 -1.1871  0.23666  \nlog(hdi)         1.4472500  0.7092888  2.0404  0.04270 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    0.24452\nResidual Sum of Squares: 0.22795\nR-Squared:      0.067783\nAdj. R-Squared: -0.13444\nF-statistic: 4.58081 on 3 and 189 DF, p-value: 0.0040297\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FEM vs. Pooled OLS\npFtest(FEM, POLS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for twoways effects\n\ndata:  model1\nF = 812.75, df1 = 38, df2 = 189, p-value < 2.2e-16\nalternative hypothesis: significant effects\n```\n\n\n:::\n:::\n\n\n### Random Effects Model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nREM <- plm(model1, data = datapanel, \n                      index = c(\"province\", \"year\"), \n                      effect = \"twoways\", model = \"random\")\nsummary(REM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects Random Effect Model \n   (Swamy-Arora's transformation)\n\nCall:\nplm(formula = model1, data = datapanel, effect = \"twoways\", model = \"random\", \n    index = c(\"province\", \"year\"))\n\nBalanced Panel: n = 33, T = 7, N = 231\n\nEffects:\n                   var  std.dev share\nidiosyncratic 0.001206 0.034728 0.008\nindividual    0.141041 0.375555 0.992\ntime          0.000000 0.000000 0.000\ntheta: 0.9651 (id) 0 (time) 0 (total)\n\nResiduals:\n      Min.    1st Qu.     Median    3rd Qu.       Max. \n-0.1099833 -0.0205049  0.0012902  0.0165381  0.1635731 \n\nCoefficients:\n                   Estimate  Std. Error z-value Pr(>|z|)    \n(Intercept)     -2.1127e+01  1.0047e+00 -21.029   <2e-16 ***\nlog(population)  8.9072e-01  7.1716e-02  12.420   <2e-16 ***\nlog(investment)  9.0107e-04  4.1329e-03   0.218   0.8274    \nlog(hdi)         4.5687e+00  2.2971e-01  19.889   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    3.599\nResidual Sum of Squares: 0.35333\nR-Squared:      0.90183\nAdj. R-Squared: 0.90053\nChisq: 2085.22 on 3 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n### Hausman Test\n\n::: {.cell}\n\n```{.r .cell-code}\nphtest(FEM,REM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHausman Test\n\ndata:  model1\nchisq = 46.609, df = 3, p-value = 4.208e-10\nalternative hypothesis: one model is inconsistent\n```\n\n\n:::\n:::\n\n\n### Model Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Multicolinearity\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(POLS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog(population) log(investment)        log(hdi) \n       1.596289        1.641147        1.119590 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor(datapanel[,4:6])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           population investment       hdi\npopulation  1.0000000  0.7052198 0.1212988\ninvestment  0.7052198  1.0000000 0.3222325\nhdi         0.1212988  0.3222325 1.0000000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmtest)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: zoo\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'zoo'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    as.Date, as.Date.numeric\n```\n\n\n:::\n\n```{.r .cell-code}\n# Heteroscedasticity\nbptest(FEM) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  FEM\nBP = 32.396, df = 3, p-value = 4.319e-07\n```\n\n\n:::\n\n```{.r .cell-code}\n# Autocorrelation\npbgtest(FEM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBreusch-Godfrey/Wooldridge test for serial correlation in panel models\n\ndata:  model1\nchisq = 84.76, df = 7, p-value = 1.468e-15\nalternative hypothesis: serial correlation in idiosyncratic errors\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cluster Robust Standard Error\nlibrary(sandwich)\ncoeftest(FEM, vcovHC(FEM, type = \"sss\", cluster = \"group\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                  Estimate Std. Error t value Pr(>|t|)\nlog(population) -0.4403249  0.4093013 -1.0758   0.2834\nlog(investment) -0.0046652  0.0056843 -0.8207   0.4128\nlog(hdi)         1.4472500  1.0807171  1.3392   0.1821\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# HAC Robust Standard Error\ncoeftest(FEM, vcovHC(FEM, method=\"arellano\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                  Estimate Std. Error t value Pr(>|t|)\nlog(population) -0.4403249  0.4012959 -1.0973   0.2739\nlog(investment) -0.0046652  0.0055732 -0.8371   0.4036\nlog(hdi)         1.4472500  1.0595795  1.3659   0.1736\n```\n\n\n:::\n:::\n\n\n## Dynamic Panel Data\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(datapanel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province  year realgdp population investment   hdi\n  <chr>    <dbl>   <dbl>      <dbl>      <dbl> <dbl>\n1 Aceh      2010 101545.    4523100       82.3  67.1\n2 Aceh      2011 104874.    4619000      463.   67.4\n3 Aceh      2012 108915.    4715100     1726.   67.8\n4 Aceh      2013 111756.    4811100     4785.   68.3\n5 Aceh      2014 113488.    4906800     5497.   68.8\n6 Aceh      2015 112672.    5002000     4485.   69.4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lag(log(realgdp), 2:7) = Instrument\nmodeldyn1 = log(realgdp) ~ lag(log(realgdp)) + log(population) + log(investment) + log(hdi) | lag(log(realgdp),2:7) \n# Dynamic OLS and FEM\nmodeldyn2 = log(realgdp) ~ lag(log(realgdp)) + log(population) + log(investment) + log(hdi)\n```\n:::\n\n\n### First Difference GMM\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfd.gmm = pgmm(modeldyn1, data = datapanel)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in pgmm(modeldyn1, data = datapanel): the second-step matrix is\nsingular, a general inverse is used\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fd.gmm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in vcovHC.pgmm(object): a general inverse is used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects One-step model Difference GMM \n\nCall:\npgmm(formula = modeldyn1, data = datapanel)\n\nBalanced Panel: n = 33, T = 7, N = 231\n\nNumber of Observations Used: 165\nResiduals:\n      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. \n-0.0926516 -0.0071905 -0.0006685  0.0000000  0.0051944  0.1291078 \n\nCoefficients:\n                    Estimate Std. Error z-value  Pr(>|z|)    \nlag(log(realgdp))  0.7312958  0.2057587  3.5541 0.0003792 ***\nlog(population)   -0.1750407  0.1798151 -0.9734 0.3303305    \nlog(investment)    0.0013969  0.0022465  0.6218 0.5340580    \nlog(hdi)           2.1197608  1.3035304  1.6262 0.1039137    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSargan test: chisq(14) = 25.4339 (p-value = 0.030518)\nAutocorrelation test (1): normal = -1.836971 (p-value = 0.066214)\nAutocorrelation test (2): normal = 1.555262 (p-value = 0.11988)\nWald test for coefficients: chisq(4) = 95.86464 (p-value = < 2.22e-16)\nWald test for time dummies: chisq(5) = 8.364699 (p-value = 0.13725)\n```\n\n\n:::\n:::\n\n\n### System GMM\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsys.gmm = pgmm(modeldyn1, data = datapanel, transformation=\"ld\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in pgmm(modeldyn1, data = datapanel, transformation = \"ld\"): the\nsecond-step matrix is singular, a general inverse is used\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(sys.gmm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in vcovHC.pgmm(object): a general inverse is used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects One-step model System GMM \n\nCall:\npgmm(formula = modeldyn1, data = datapanel, transformation = \"ld\")\n\nBalanced Panel: n = 33, T = 7, N = 231\n\nNumber of Observations Used: 363\nResiduals:\n      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. \n-0.1198240 -0.0083907  0.0001403  0.0000000  0.0065018  0.1402918 \n\nCoefficients:\n                   Estimate Std. Error z-value  Pr(>|z|)    \nlag(log(realgdp)) 0.9686425  0.0107842 89.8208 < 2.2e-16 ***\nlog(population)   0.0207419  0.0078302  2.6490  0.008074 ** \nlog(investment)   0.0070513  0.0029150  2.4190  0.015565 *  \nlog(hdi)          0.1144280  0.0582058  1.9659  0.049308 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSargan test: chisq(22) = 23.67029 (p-value = 0.36475)\nAutocorrelation test (1): normal = -1.663193 (p-value = 0.096274)\nAutocorrelation test (2): normal = 1.368565 (p-value = 0.17114)\nWald test for coefficients: chisq(4) = 314880.1 (p-value = < 2.22e-16)\nWald test for time dummies: chisq(5) = 29.57621 (p-value = 1.7869e-05)\n```\n\n\n:::\n:::\n\n\n### Model Diagnotics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FEM\nFEMdyn = plm(modeldyn2, data = datapanel, index=c(\"province\",\"year\"), model=\"within\")\nsummary(FEMdyn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = modeldyn2, data = datapanel, model = \"within\", \n    index = c(\"province\", \"year\"))\n\nBalanced Panel: n = 33, T = 6, N = 198\n\nResiduals:\n       Min.     1st Qu.      Median     3rd Qu.        Max. \n-5.8397e-02 -6.5483e-03  1.4102e-05  5.9536e-03  1.1759e-01 \n\nCoefficients:\n                    Estimate Std. Error t-value  Pr(>|t|)    \nlag(log(realgdp))  0.7670629  0.0397433 19.3004 < 2.2e-16 ***\nlog(population)   -0.2488432  0.1100829 -2.2605   0.02513 *  \nlog(investment)   -0.0014210  0.0024243 -0.5861   0.55862    \nlog(hdi)           1.8786968  0.2913007  6.4493 1.253e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    1.9728\nResidual Sum of Squares: 0.050149\nR-Squared:      0.97458\nAdj. R-Squared: 0.96889\nF-statistic: 1543.1 on 4 and 161 DF, p-value: < 2.22e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# OLS\nOLSdyn = plm(modeldyn2, data = datapanel, index=c(\"province\",\"year\"), model=\"pooling\")\nsummary(OLSdyn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPooling Model\n\nCall:\nplm(formula = modeldyn2, data = datapanel, model = \"pooling\", \n    index = c(\"province\", \"year\"))\n\nBalanced Panel: n = 33, T = 6, N = 198\n\nResiduals:\n       Min.     1st Qu.      Median     3rd Qu.        Max. \n-0.10036444 -0.00975944 -0.00044271  0.00946369  0.12897120 \n\nCoefficients:\n                    Estimate Std. Error  t-value Pr(>|t|)    \n(Intercept)       -0.1070843  0.1261711  -0.8487  0.39709    \nlag(log(realgdp))  0.9868710  0.0041424 238.2382  < 2e-16 ***\nlog(population)    0.0088980  0.0036806   2.4175  0.01656 *  \nlog(investment)    0.0016145  0.0016016   1.0080  0.31470    \nlog(hdi)           0.0397307  0.0297085   1.3374  0.18268    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    269.87\nResidual Sum of Squares: 0.09922\nR-Squared:      0.99963\nAdj. R-Squared: 0.99962\nF-statistic: 131187 on 4 and 193 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\nFDGMM = 0.731 \nSysGMM = 0.968 \nFEM = 0.767 \nOLS = 0.986\n\nFEM < GMM < OLS\nBest Model: System GMM\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sys.gmm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in vcovHC.pgmm(object): a general inverse is used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects One-step model System GMM \n\nCall:\npgmm(formula = modeldyn1, data = datapanel, transformation = \"ld\")\n\nBalanced Panel: n = 33, T = 7, N = 231\n\nNumber of Observations Used: 363\nResiduals:\n      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. \n-0.1198240 -0.0083907  0.0001403  0.0000000  0.0065018  0.1402918 \n\nCoefficients:\n                   Estimate Std. Error z-value  Pr(>|z|)    \nlag(log(realgdp)) 0.9686425  0.0107842 89.8208 < 2.2e-16 ***\nlog(population)   0.0207419  0.0078302  2.6490  0.008074 ** \nlog(investment)   0.0070513  0.0029150  2.4190  0.015565 *  \nlog(hdi)          0.1144280  0.0582058  1.9659  0.049308 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSargan test: chisq(22) = 23.67029 (p-value = 0.36475)\nAutocorrelation test (1): normal = -1.663193 (p-value = 0.096274)\nAutocorrelation test (2): normal = 1.368565 (p-value = 0.17114)\nWald test for coefficients: chisq(4) = 314880.1 (p-value = < 2.22e-16)\nWald test for time dummies: chisq(5) = 29.57621 (p-value = 1.7869e-05)\n```\n\n\n:::\n:::\n\n\n### Speed of Adjustment\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha1 = sys.gmm$coef[1]\n1-alpha1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlag(log(realgdp)) \n       0.03135749 \n```\n\n\n:::\n:::\n\n\n### Half Time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog(0.5)/log(sys.gmm$coef[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlag(log(realgdp)) \n         21.75626 \n```\n\n\n:::\n:::\n\n\n### Short Run and Long Run Coefficients\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsys.gmm$coefficients[2] # Short Run Poppulation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog(population) \n     0.02074192 \n```\n\n\n:::\n\n```{.r .cell-code}\nsys.gmm$coefficients[2] / (1-alpha1) # Long Run Poppulation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog(population) \n      0.6614661 \n```\n\n\n:::\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}